#
# For full config options, check the docs:
#    docs.serverless.com
#

service: example-authorizer

custom:
  config: ${file(./config.yml)}

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${self:custom.config.stage}
  region: ${self:custom.config.region}
  memorySize: 128
  stackTags:
    DEPLOYMENT: serverless-framework

functions:
  getDogs:
    description: Gets dogs data
    handler: src/getDogs.handler
    events:
      - http:
          path: /dogs
          method: get
          authorizer: authorizerFunc
  authorizerFunc:
    handler: src/authorizer.handler
  getCats:
    description: Gets cats data
    handler: src/getCats.handler
    events:
      - http:
          path: /cats
          method: get
          authorizer: authorizerCatsFunc
  authorizerCatsFunc:
    handler: src/authorizerCats.handler
